config/routes.rb
Rails.application.routes.draw do
  resources :products
  get "index", to: 'welcome#index'
  get "about", to: 'welcome#about'

  devise_for :users

  root "welcome#index"
end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :price, numericality: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:cod, :name, :quantity, :image, :description, :price)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title Inventario
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'default', 'data-turbolinks-track' => true
		= csrf_meta_tags
	%body
		%nav.navbar.navbar-default
			.container-fluid
				/ Brand and toggle get grouped for better mobile display
				.navbar-header
					%button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
						%span.sr-only Toggle navigation
						%span.icon-bar
						%span.icon-bar
						%span.icon-bar
					%a.navbar-brand{:href => "#"} Inventario
				/ Collect the nav links, forms, and other content for toggling
				#bs-example-navbar-collapse-1.collapse.navbar-collapse
					%ul.nav.navbar-nav
						%li.active
							= link_to "Home", root_path
						%li
							= link_to "About", about_path
						-	unless current_user
							%li
								=	link_to "Acceso", new_user_session_path
							%li
								=	link_to "Registrarse", new_user_registration_path
						-	else
							%li
								=	link_to "Productos", products_path
							%li
								= link_to "Cerrar Sesion", destroy_user_session_path, method: "delete"
				/ /.navbar-collapse
			/ /.container-fluid
		.container
			= yield

app/views/products/_form.html.haml
=	simple_form_for(@product)	do|f|
	=	f.error_notification

	.form-inputs
		= f.input :cod, label: "Codigo"
		= f.input :name, label: "Nombre"
		= f.input :quantity, label: "Cantidad", hint: "Mantener mas de 50 en stock...", as: :float
		= f.input :image, label: "Imagen", as: :file
		= f.input :description, label: "Descripcion", as: :text
		= f.input :price, label: "Precio"
	.form-actions
		= f.button :submit

app/views/products/edit.html.haml
%h1 Editar Producto

= render 'form'

= link_to 'Mostrar', @product
\|
= link_to 'Atras', products_path

app/views/products/index.html.haml
%h1 Listado de Productos

.table-responsive
  %table.table
    %thead
      %tr
        %th Codigo 
        %th Nombre
        %th Cantidad
        %th Imagen
        %th Descripcion
        %th Precio
      
    %tbody
      - @products.each do |product|
        %tr{ class: "#{product.quantity <= 50 ? 'danger' : 'success'}" }
          %td= product.cod
          %td= product.name
          %td= product.quantity
          %td= product.image
          %td= product.description
          %td= product.price
          %td= link_to 'Mostrar', product
          %td= link_to 'Editar', edit_product_path(product)
          %td= link_to 'Eliminar', product, :method => :delete, :data => { :confirm => '¿Estas seguro?' }

  %br

  = link_to 'Nuevo Producto', new_product_path

app/views/products/new.html.haml
%h1 Nuevo producto

= render 'form'

= link_to 'Atras', products_path

app/views/products/show.html.haml
%p#notice= notice

%p
  %b Codigo:
  = @product.cod
%p
  %b Nombre:
  = @product.name
%p
  %b Cantidad:
  = @product.quantity
%p
  %b Imagen:
  = @product.image
%p
  %b Descripcion:
  = @product.description
%p
  %b Precio:
  = @product.price

= link_to 'Editar', edit_product_path(@product)
\|
= link_to 'Atras', products_path

app/views/welcome/about.html.haml
%h1	Acerca de...

app/views/welcome/index.html.haml
%h1 Bienvenidos